# Generated by Django 4.0.5 on 2022-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_io', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='image_id'),
        ),
    ]
