# Generated by Django 4.0.5 on 2022-06-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='image_id')),
                ('name', models.CharField(max_length=500, verbose_name='image_name')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
